

server:
  port: 8001

spring:
  application:
    name: Product
  boot:
    admin:
      client:
        url: http://localhost:8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
