version: "3.3"

services:

  redis:
    image: redis:alpine
    container_name: pg-redis
    restart: always
    volumes:
      - ../data/redis:/data
    environment:
      - REDIS_PASSWORD=123456
    networks:
      - backend
    ports:
      - 6379:6379
    env_file: .env

  config-server:
    image: playground/config-server:1.0.1
    container_name: pg-config-server
    networks:
      - backend
    restart: always
    env_file: .env
    environment:
      - GIT_URI=https://github.com/jinfang134/springcloud-playground-config
    ports:
      - "8888:8888"


networks:
  backend:
    external: false