version: "3.3"

services:

  api-gateway:
    image: playground/api-gateway:1.0.1
    container_name: pg-api-gateway
    restart: always
    env_file: .env
    ports:
      - "8080:8080"
    networks:
      - backend


#  eureka:
#    image: playground/eureka:1.0.1
#    container_name: pg-eureka
#    restart: always
#    env_file: .env
#    ports:
#      - "8761:8761"
#    networks:
#      - backend

#  admin:
#    image: playground/admin:1.0.1
#    container_name: pg-admin
##    restart: always
#    env_file: .env
#    ports:
#      - "8000:8000"
#    networks:
#      - backend

  redis:
    image: redis:alpine
    container_name: pg-redis
    restart: always
    volumes:
      - ../data/redis:/data
    environment:
      - REDIS_PASSWORD=123456
    networks:
      - backend
    ports:
      - 6379:6379
    env_file: .env

#  zipkin:
#    image: openzipkin/zipkin-slim
#    container_name: pg-zipkin
##    restart: always
#    env_file: .env
#    ports:
#      - "9411:9411"
#    networks:
#      - backend

networks:
  backend:
    external: false