

server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: ${GIT_URI:https://github.com/jinfang134/springcloud-playground-config}
#          username:
#          password:
